/** Kenya counties (47) plus common estates / towns people search for housing. */

export const KENYA_COUNTIES = [
  "Baringo",
  "Bomet",
  "Bungoma",
  "Busia",
  "Elgeyo-Marakwet",
  "Embu",
  "Garissa",
  "Homa Bay",
  "Isiolo",
  "Kajiado",
  "Kakamega",
  "Kericho",
  "Kiambu",
  "Kilifi",
  "Kirinyaga",
  "Kisii",
  "Kisumu",
  "Kitui",
  "Kwale",
  "Laikipia",
  "Lamu",
  "Machakos",
  "Makueni",
  "Mandera",
  "Marsabit",
  "Meru",
  "Migori",
  "Mombasa",
  "Murang'a",
  "Nairobi",
  "Nakuru",
  "Nandi",
  "Narok",
  "Nyamira",
  "Nyandarua",
  "Nyeri",
  "Samburu",
  "Siaya",
  "Taita-Taveta",
  "Tana River",
  "Tharaka-Nithi",
  "Trans Nzoia",
  "Turkana",
  "Uasin Gishu",
  "Vihiga",
  "Wajir",
  "West Pokot",
] as const;

export type KenyaCounty = (typeof KENYA_COUNTIES)[number];

const AREAS: Record<string, string[]> = {
  Nairobi: [
    "CBD",
    "Westlands",
    "Kilimani",
    "Kileleshwa",
    "Lavington",
    "Karen",
    "Langata",
    "South B",
    "South C",
    "Nairobi West",
    "Ngong Road",
    "Upper Hill",
    "Parklands",
    "Highridge",
    "Kasarani",
    "Roysambu",
    "Zimmerman",
    "Kahawa West",
    "Kahawa Sukari",
    "Githurai",
    "Pipeline",
    "Embakasi",
    "Donholm",
    "Umoja",
    "Kayole",
    "Eastleigh",
    "Pangani",
    "Ngara",
    "Hurlingham",
    "Kilimani / State House",
    "Ruiru Road / Garden Estate",
    "Runda",
    "Gigiri",
    "Muthaiga",
    "Spring Valley",
    "Loresho",
    "Kangemi",
    "Kawangware",
    "Dagoretti",
    "Kibera",
    "Madaraka",
    "Nyayo Estate",
    "Fedha",
    "Utawala",
    "Ruai",
    "Kamulu",
    "Imara Daima",
    "South C / Bellevue",
  ],
  Kiambu: [
    "Thika",
    "Ruiru",
    "Juja",
    "Kikuyu",
    "Limuru",
    "Kiambu Town",
    "Karuri",
    "Githunguri",
    "Kahawa Sukari",
    "Kahawa Wendani",
    "Membley",
    "Kamakis",
    "Kimbo",
    "Witeithie",
    "Ruiru Bypass",
    "Tatu City",
    "Runda Mimosa",
    "Banana Hill",
    "Wangige",
    "Ongata Rongai (border)",
  ],
  Machakos: [
    "Machakos Town",
    "Athi River",
    "Mavoko",
    "Syokimau",
    "Mlolongo",
    "Katani",
    "Joska",
    "Kangundo",
    "Tala",
    "Malaa",
    "Kyumbi",
    "Kinanie",
  ],
  Kajiado: [
    "Kitengela",
    "Ongata Rongai",
    "Ngong",
    "Kiserian",
    "Isinya",
    "Kajiado Town",
    "Namanga Road",
    "Oloitokitok",
    "Kitengela / Acacia",
    "Rongai / Tuala",
  ],
  Mombasa: [
    "Mombasa CBD",
    "Nyali",
    "Bamburi",
    "Kisauni",
    "Likoni",
    "Changamwe",
    "Mikindani",
    "Mtwapa (border)",
    "Shanzu",
    "Tudor",
    "Old Town",
    "Bombolulu",
  ],
  Nakuru: [
    "Nakuru Town",
    "Milimani",
    "Section 58",
    "Naka",
    "Lanet",
    "Pipeline Nakuru",
    "Free Area",
    "Shabab",
    "Naivasha",
    "Gilgil",
    "Mai Mahiu",
    "Molo",
  ],
  Kisumu: [
    "Kisumu CBD",
    "Milimani",
    "Nyalenda",
    "Kondele",
    "Mamboleo",
    "Tom Mboya",
    "Kibos",
    "Dunga",
    "Riat",
  ],
  "Uasin Gishu": ["Eldoret", "Langas", "Elgon View", "West Indies", "Kapsoya", "Huruma", "Maili Nne"],
  Kilifi: ["Kilifi Town", "Malindi", "Watamu", "Mtwapa", "Vipingo", "Mariakani", "Kaloleni"],
  Kwale: ["Ukunda", "Diani", "Msambweni", "Kwale Town", "Lunga Lunga"],
  Kisii: ["Kisii Town", "Nyamataro", "Daraja Mbili"],
  Meru: ["Meru Town", "Nkubu", "Maua", "Timau"],
  Nyeri: ["Nyeri Town", "Karatina", "Othaya", "Mweiga"],
  Kakamega: ["Kakamega Town", "Lurambi", "Mumias"],
  Bungoma: ["Bungoma Town", "Webuye", "Kimilili"],
  Kericho: ["Kericho Town", "Litein", "Kapkatet"],
  Laikipia: ["Nanyuki", "Nyahururu", "Rumuruti"],
  Narok: ["Narok Town", "Mai Mahiu Road", "Kilgoris"],
  "Murang'a": ["Murang'a Town", "Kenol", "Kangema", "Maragua"],
  Kirinyaga: ["Kerugoya", "Sagana", "Kutus", "Wang'uru"],
  Embu: ["Embu Town", "Runyenjes", "Siakago"],
  Kitui: ["Kitui Town", "Mwingi", "Kitui CBD"],
  Makueni: ["Wote", "Mtito Andei", "Email", "Kibwezi"],
  Nyandarua: ["Ol Kalou", "Engineer", "Nyahururu Road"],
  Bomet: ["Bomet Town", "Sotik"],
  Nandi: ["Kapsabet", "Nandi Hills"],
  "Trans Nzoia": ["Kitale", "Endebess"],
  "Elgeyo-Marakwet": ["Iten", "Tambach"],
  "Homa Bay": ["Homa Bay Town", "Mbita", "Oyugis"],
  Migori: ["Migori Town", "Rongo", "Isebania"],
  Siaya: ["Siaya Town", "Bondo", "Ugunja"],
  Vihiga: ["Mbale", "Luanda", "Chavakali"],
  Busia: ["Busia Town", "Malaba"],
  "Taita-Taveta": ["Voi", "Wundanyi", "Taveta", "Mwatate"],
  Garissa: ["Garissa Town"],
  Isiolo: ["Isiolo Town"],
  Marsabit: ["Marsabit Town", "Moyale"],
  Mandera: ["Mandera Town"],
  Wajir: ["Wajir Town"],
  Turkana: ["Lodwar", "Kakuma"],
  Samburu: ["Maralal"],
  "West Pokot": ["Kapenguria"],
  Baringo: ["Kabarnet", "Eldama Ravine"],
  "Tharaka-Nithi": ["Chuka", "Marimanti"],
  "Tana River": ["Hola", "Garsen"],
  Lamu: ["Lamu Town", "Mpeketoni"],
  Nyamira: ["Nyamira Town", "Keroka"],
};

export function areasForCounty(county: string): string[] {
  return AREAS[county] ?? [];
}

export function formatPlaceLabel(county: string, locality?: string): string {
  const loc = locality?.trim();
  if (loc && county) return `${loc}, ${county}`;
  return county || loc || "";
}
